// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SBExplorer
{
    internal sealed partial class Vsix
    {
        public const string Id = "SBExplorer.1966f8a4-7fd6-4d7c-a3ec-cf644aca4aad";
        public const string Name = "SBExplorer";
        public const string Description = @"ServiceBus Explorer Extension";
        public const string Language = "en-US";
        public const string Version = "2.4";
        public const string Author = "Kelvys Boniek Pantaleão";
        public const string Tags = "";
    }
}
